import Head from 'next/head'
import Body from '../components/body'
import Header from '../components/header'
import Popup from '../components/popup'
import styles from '../styles/Home.module.css'
import { useContext, useEffect, useState } from 'react'
import AppContext from '../components/appcontext'
import Router from 'next/router'

export default function Home() {
  const { userData, setUserData } = useContext(AppContext);

  const [usePopup, setUsePopup] = useState(false);
  const [popUpAction, setpopUpAction] = useState('none');
  const [images, setImages] = useState([]);
  const [idImage, setidImage] = useState([]);

  useEffect(() => {
    if (userData.username && userData.username != '') return;

    const ls = localStorage.getItem('cr');
    const _userData = JSON.parse(ls);
    
    if (!_userData || _userData.username) {
      Router.replace('/');
    };

    setUserData(_userData)
  }, [])

  useEffect(() => {
    if ( !userData ) {
      Router.replace('/login');
      return
    }
    fetch(
      `${process.env.NEXT_PUBLIC_API_URL}api/images/${userData.id}`, {
        headers: {
          "Authorization": `Token ${userData.token}`
        }
      }
    )
      .then(response => response.json())
      .then(response => {
        console.log(response)
        setImages(response)
      })
      .catch(err => err)
  }, [usePopup, userData])

  return (
    <div className={styles.container}>
      <Head>
        <title>My Unsplash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div 
        className={`${styles.Curtain} ${usePopup ? styles.Curtain_on : ''}`}
        onClick={(e) => setUsePopup(false)}
      >
      </div>
      <Header 
        data={{
          setUsePopup,
          setpopUpAction,
          userData
        }}
      />
      <Body 
        data={{
          setUsePopup,
          setpopUpAction,
          images,
          setidImage
        }}
      />
      <Popup 
        data={{
          usePopup,
          setUsePopup,
          popUpAction,
          idImage,
          userData
        }}
      />
    </div>
  )
}