import Head from 'next/head'
import Image from 'next/image'
import Body from '../components/body'
import Header from '../components/header'
import Popup from '../components/popup'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home() {

  const [usePopup, setUsePopup] = useState(false);
  const [popUpAction, setpopUpAction] = useState('none');

  return (
    <div className={styles.container}>
      <Head>
        <title>My Unsplash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`${styles.Curtain} ${usePopup ? styles.Curtain_on : ''}`}>
      </div>
      <Header />
      <Body 
        data={{
          setUsePopup,
          setpopUpAction
        }}
      />
      <Popup 
        data={{
          usePopup,
          setUsePopup,
          popUpAction
        }}
      />
    </div>
  )
}
